version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: versmos-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: versmos
      POSTGRES_PASSWORD: versmos_dev_2024
      POSTGRES_DB: versmos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U versmos"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: